"""Added year_founded to Company

Revision ID: 086b67d89f47
Revises: 
Create Date: 2022-07-04 08:48:14.363507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086b67d89f47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('year_founded', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'year_founded')
    # ### end Alembic commands ###
