"""Added index for Employee.job

Revision ID: 24325e7f766a
Revises: e084bea24ce6
Create Date: 2022-07-04 12:11:51.851177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24325e7f766a'
down_revision = 'e084bea24ce6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_employees_job'), 'employees', ['job'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_job'), table_name='employees')
    # ### end Alembic commands ###
